spring:

  profiles:
    active: dev
  redis:
    host: localhost
    database: 0
    password:
    port: 6379
    jedis:
      pool:
        max-active: -1
        max-idle: 30
        min-idle: 0
  cache:
      ehcache:
        config: ehcache.xml
      cache-names:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springboottest?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小，最小，最大
    initialSize: 1
    maxActive: 20
    minIdle: 1
    #最大连接等待超时时间
    maxWait: 60000
    #配置多久进行一次检测需要关闭的连接时间（毫秒）
    timeBetweenEvictionRunsMillis: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #一个连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    #重连配置
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,slf4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
